/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ftdca;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mahedi Hasan
 */
public class EditInfo extends javax.swing.JFrame {

    //for database
    Connection cn = null;
    Statement stmt = null;
    String driver = "com.mysql.jdbc.Driver";
    String url = "jdbc:mysql://localhost:3306/ftdca";
    
     //Credentials
    private static String Password, Email, sql;  //user
    private static String ConsumerKey, ConsumerKeySecret, AccessToken, AccessTokenSecret; //Twitter
    private static String AppId, AppSecret; //Facebook
    
    
    
    
    
    /**
     * Creates new form EditInfo
     */
    public EditInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ConsumerKeyField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ConsumerKeySecretField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AccessTokenField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AccessTokenSecretField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AppIdField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        AppSecretField = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        MenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 3, 18)); // NOI18N
        jLabel1.setText("Enter Which Credentials You Want to Edit");

        jLabel2.setText("Enter New Password");

        jLabel3.setText("Enter New ConsumerKey");

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 3, 14)); // NOI18N
        jLabel4.setText("Enter below 4 items if you want to change twitters credentials");

        jLabel5.setText("Enter New ConsumerKeySecret");

        jLabel6.setText("Enter New AccessToken");

        jLabel7.setText("Enter New AccessTokenSecret");

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 3, 14)); // NOI18N
        jLabel8.setText("Enter below 2 items if you want to change facebook's credentials");

        jLabel9.setText("Enter New AppId");

        jLabel10.setText("Enter New AppSecret");

        SubmitButton.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 3, 14)); // NOI18N
        jLabel11.setText("Enter New Password if you want to change");

        MenuButton.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        MenuButton.setText("Menu");
        MenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ConsumerKeyField)
                    .addComponent(ConsumerKeySecretField)
                    .addComponent(AccessTokenField)
                    .addComponent(AccessTokenSecretField)
                    .addComponent(PasswordField)
                    .addComponent(AppIdField)
                    .addComponent(AppSecretField, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 212, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(348, 348, 348))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(389, 389, 389))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(276, 276, 276))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(266, 266, 266))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsumerKeyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsumerKeySecretField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(AccessTokenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AccessTokenSecretField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AppIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(AppSecretField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        try {
            //getting the email from the GetCredentials page
            GetCredentials g = new GetCredentials();
            Email = g.GetEmail();
            
            //get these info from EditInfo form
            Password = PasswordField.getText();
            
            //followings are for twitter
            ConsumerKey = ConsumerKeyField.getText();
            ConsumerKeySecret = ConsumerKeySecretField.getText();
            AccessToken = AccessTokenField.getText();
            AccessTokenSecret = AccessTokenSecretField.getText();
            
            //followings are for facebook
            AppId = AppIdField.getText();
            AppSecret = AppSecretField.getText();
            
            //connect to mysql
            cn = DriverManager.getConnection(url, "root", "");
            stmt = cn.createStatement(); //create a statement to execute query
            
            //if password field is not empty
            if(!Password.isEmpty()){
                sql = "UPDATE `registration` SET `Password` = '"+Password+"' WHERE Email='"+Email+"'"; //update query
                if(stmt.execute(sql) == false){
                    JOptionPane.showMessageDialog(null, "Successfully Changed Password!");
                }
            }
            
            //if twitter credentials are not empty
            if(!ConsumerKey.isEmpty() && !ConsumerKeySecret.isEmpty() && !AccessToken.isEmpty() && !AccessTokenSecret.isEmpty()){
                sql = "UPDATE `registration` SET `ConsumerKey` = '"+ConsumerKey+"', `ConsumerKeySecret` = '"+ConsumerKeySecret+"', `AccessToken` = '"+AccessToken+"', `AccessTokenSecret` = '"+AccessTokenSecret +"' WHERE Email='"+Email+"'";
                if(stmt.execute(sql) == false){
                    JOptionPane.showMessageDialog(null, "Successfully Changed Twitter Credentials!");
                }
            }
            
            //if fb credentials are not empty
            if(!AppId.isEmpty() && !AppSecret.isEmpty()){
                sql = "UPDATE `registration` SET `AppId` = '"+AppId+"', `AppSecret` = '"+AppSecret+"' WHERE Email='"+Email+"'";
                if(stmt.execute(sql) == false){
                    JOptionPane.showMessageDialog(null, "Successfully Changed Facebook Credentials!");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(EditInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void MenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuButtonActionPerformed
        this.setVisible(false); //hiding the current page
        Menu menu = new Menu(); //creating a menu page
        menu.setVisible(true); //showing the menu page
    }//GEN-LAST:event_MenuButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccessTokenField;
    private javax.swing.JTextField AccessTokenSecretField;
    private javax.swing.JTextField AppIdField;
    private javax.swing.JTextField AppSecretField;
    private javax.swing.JTextField ConsumerKeyField;
    private javax.swing.JTextField ConsumerKeySecretField;
    private javax.swing.JButton MenuButton;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
